/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as AdminTep2026RouteImport } from './routes/admin-tep2026'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AlumniIdRouteImport } from './routes/alumni.$id'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTep2026Route = AdminTep2026RouteImport.update({
  id: '/admin-tep2026',
  path: '/admin-tep2026',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoriesRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const AlumniIdRoute = AlumniIdRouteImport.update({
  id: '/alumni/$id',
  path: '/alumni/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-tep2026': typeof AdminTep2026Route
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stories': typeof StoriesRouteWithChildren
  '/alumni/$id': typeof AlumniIdRoute
  '/events/$id': typeof EventsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/events/': typeof EventsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-tep2026': typeof AdminTep2026Route
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/alumni/$id': typeof AlumniIdRoute
  '/events/$id': typeof EventsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/events': typeof EventsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-tep2026': typeof AdminTep2026Route
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stories': typeof StoriesRouteWithChildren
  '/alumni/$id': typeof AlumniIdRoute
  '/events/$id': typeof EventsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/events/': typeof EventsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-tep2026'
    | '/directory'
    | '/events'
    | '/login'
    | '/register'
    | '/stories'
    | '/alumni/$id'
    | '/events/$id'
    | '/stories/$id'
    | '/events/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-tep2026'
    | '/directory'
    | '/login'
    | '/register'
    | '/alumni/$id'
    | '/events/$id'
    | '/stories/$id'
    | '/events'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/admin-tep2026'
    | '/directory'
    | '/events'
    | '/login'
    | '/register'
    | '/stories'
    | '/alumni/$id'
    | '/events/$id'
    | '/stories/$id'
    | '/events/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminTep2026Route: typeof AdminTep2026Route
  DirectoryRoute: typeof DirectoryRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  AlumniIdRoute: typeof AlumniIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tep2026': {
      id: '/admin-tep2026'
      path: '/admin-tep2026'
      fullPath: '/admin-tep2026'
      preLoaderRoute: typeof AdminTep2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/alumni/$id': {
      id: '/alumni/$id'
      path: '/alumni/$id'
      fullPath: '/alumni/$id'
      preLoaderRoute: typeof AlumniIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface StoriesRouteChildren {
  StoriesIdRoute: typeof StoriesIdRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesIdRoute: StoriesIdRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminTep2026Route: AdminTep2026Route,
  DirectoryRoute: DirectoryRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StoriesRoute: StoriesRouteWithChildren,
  AlumniIdRoute: AlumniIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
